// Optional end-to-end test. Set PLAYWRIGHT_MODULE to an installed Playwright path.
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_URL||'http://localhost:4175/Setka/';
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-06T08:00:00Z'));const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('artifacts',{recursive:true});
try{
  await page.goto(base);await page.locator('#dialog[open]').waitFor();await page.locator('#dialog [data-action=close]').click();
  await page.waitForSelector('.now-panel');
  const parsed=await page.evaluate(async()=>{
    const {readXlsx}=await import('./src/import/xlsx.js');const {inferMipt}=await import('./src/import/mipt.js');
    const data=await (await fetch('./fixtures/mipt/File.xlsx')).arrayBuffer();const ir=await readXlsx(data,'File.xlsx');const result=inferMipt(ir);
    return {result,irSummary:ir.sheets.map(s=>({name:s.name,cells:s.cells.length,merges:s.merges.length}))};
  });
  console.log('Workbook:',JSON.stringify({sheets:parsed.irSummary,groups:parsed.result.groups.length,blocks:parsed.result.importMeta.blocks.length,series:parsed.result.series.length}));
  const group=parsed.result.series.filter(s=>s.cohorts.some(c=>c.groupId==='Б01-601'));
  const byRange=r=>group.find(s=>s.source.ranges.includes(r));
  assert.equal(byRange('C12:C13').location,'515 ГК');
  assert.equal(byRange('C10:K11').cohorts.length,9);
  assert.deepEqual(byRange('C47:C49').time,{startsAt:'09:00',endsAt:'12:00',slotNumbers:[1,2]});
  assert.deepEqual(byRange('C64:C66').time,{startsAt:'12:10',endsAt:'15:20',slotNumbers:[3,4]});
  assert.equal(byRange('C10:K11').kind,'lecture');
  assert.equal(byRange('C12:C13').kind,'seminar');
  assert.equal(byRange('C47:C49').kind,'lab');
  assert.equal(byRange('C4:C5').kind,'class');
  assert.equal(byRange('C6:C7').kind,'sport');
  assert.equal(parsed.result.series.find(s=>s.source.ranges[0].startsWith('CK10:')).kind,'practice');
  assert.equal(parsed.result.series.find(s=>s.source.ranges[0].startsWith('AH8:')).kind,'seminar');
  assert.ok(parsed.result.series.some(s=>s.recurrence.parity==='odd'));
  assert.ok(parsed.result.series.some(s=>s.cohorts.some(c=>c.variant)));
  assert.equal(parsed.result.importMeta.blocks.length,12);
  await writeFile('artifacts/fixture-canonical.json',JSON.stringify(parsed.result,null,2));
  await page.getByRole('button',{name:'Выбрать расписание МФТИ'}).click();
  await page.locator('[data-source]').filter({hasText:'1 курс БВО'}).click();
  await page.waitForSelector('#import-form');
  await page.getByRole('button',{name:'Просмотреть изменения'}).click();
  await page.getByRole('button',{name:'Применить расписание',exact:true}).click();await page.waitForTimeout(100);
  if(await page.locator('#setup-form').count())await page.locator('#setup-form .primary').click();
  assert.equal(await page.locator('[data-action="sample-tasks"]').count(),0);
  await page.locator('[data-action="add-task"]').first().click();
  await page.locator('[name="title"]').fill('Решить задачи по механике');
  await page.getByRole('button',{name:'Добавить задачу',exact:true}).click();
  await page.locator('#day-picker').fill('2026-09-07');
  await page.waitForSelector('.event-card');
  assert.ok(await page.locator('.event-card').count()>=5);
  await page.screenshot({path:'artifacts/today-desktop.png',fullPage:true});
  const plan=page.locator('[data-action="plan"]').first();await plan.click();
  const plannedTitle=await page.locator('.plan-title').textContent();
  await page.getByRole('button',{name:'Подтвердить время'}).click();
  await page.waitForSelector('.event-card.work');
  const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')));
  assert.equal(persisted.sessions.length,1);assert.ok(persisted.tasks.some(t=>t.title===plannedTitle&&t.status==='todo'));
  await page.evaluate(async()=>{const {validateBackup}=await import('./src/storage.js');validateBackup(JSON.parse(localStorage.getItem('setka.v1')));});
  await page.reload();await page.waitForSelector('.now-panel');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')).sessions.length),1);
  await page.locator('#day-picker').fill('2026-09-07');
  await page.locator('.event-card.work').click();await page.getByRole('button',{name:'Сессия выполнена'}).click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')).sessions[0].status),'done');
  await page.locator('.sidebar [data-nav="week"]').click();
  await page.waitForSelector('.week-grid');await page.screenshot({path:'artifacts/week-desktop.png',fullPage:true});
  await page.locator('.sidebar [data-nav="more"]').click();
  await page.getByRole('button',{name:'Выбрать программу / курс'}).click();
  await page.locator('[data-source]').filter({hasText:'1 курс БВО'}).click();
  await page.getByRole('button',{name:'Просмотреть изменения'}).click();
  assert.match(await page.locator('.diff-list').innerText(),/не изменилось/);
  await page.getByRole('button',{name:'Применить расписание',exact:true}).click();await page.waitForTimeout(100);
  if(await page.locator('#setup-form').count())await page.locator('#setup-form .primary').click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')).sessions.length),1);
  await page.setViewportSize({width:390,height:844});await page.locator('#day-picker').fill('2026-09-07');
  await page.screenshot({path:'artifacts/today-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Today must not horizontally scroll');
  await page.locator('.mobile-nav [data-nav="tasks"]').click();
  await page.getByRole('button',{name:'Новая задача'}).click();
  await page.locator('[name="title"]').fill('Проверка сохранения');await page.getByRole('button',{name:'Добавить задачу',exact:true}).click();
  assert.ok(await page.getByText('Проверка сохранения',{exact:true}).count());
  await page.screenshot({path:'artifacts/tasks-mobile.png',fullPage:true});
  await page.setViewportSize({width:375,height:667});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Compact phone must not horizontally scroll');
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await context.setOffline(true);await page.reload();await page.waitForSelector('.now-panel');
  await page.locator('.mobile-nav [data-nav="tasks"]').click();
  assert.ok(await page.getByText('Проверка сохранения',{exact:true}).count());
  await page.getByRole('button',{name:'Новая задача'}).click();await page.locator('[name="title"]').fill('Офлайн-задача');await page.getByRole('button',{name:'Добавить задачу',exact:true}).click();
  assert.ok(await page.getByText('Офлайн-задача',{exact:true}).count());
  await context.setOffline(false);
  const preview=await context.newPage();await preview.goto(new URL('preview.html',base).href);
  await preview.frameLocator('iframe').locator('.now-panel').waitFor();
  assert.equal(await preview.locator('iframe').evaluate(e=>e.clientWidth),390);
  await preview.close();
  // Reopening after actual fixture lessons ended must catch up, once, without future tasks.
  await page.clock.setFixedTime(new Date('2026-09-08T18:00:00Z'));
  await page.reload();await page.waitForSelector('.now-panel');
  const generated=await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')).tasks.filter(t=>t.origin));
  for(const kind of ['lecture','seminar'])assert.ok(generated.some(t=>t.origin.kind===kind),kind+' follow-up');
  assert.ok(generated.every(t=>t.origin.date<='2026-09-08'&&t.occurrenceId&&t.status==='todo'));
  await page.reload();await page.waitForSelector('.now-panel');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('setka.v1')).tasks.filter(t=>t.origin).length),generated.length);
  await page.locator('.mobile-nav [data-nav=tasks]').click();
  await page.locator(`[data-action=manual-plan][data-id="${generated[0].id}"]`).click();
  await page.locator('#plan-form [name=date]').fill('2026-09-13');
  await page.locator('#plan-form [name=start]').fill('12:00');
  await page.locator('#plan-form [name=duration]').fill('30');
  await page.getByRole('button',{name:'Подтвердить время'}).click();
  assert.ok(await page.evaluate(id=>JSON.parse(localStorage.getItem('setka.v1')).sessions.some(s=>s.taskId===id&&s.status==='planned'),generated[0].id));
  assert.deepEqual(errors,[]);
  console.log('PASS: real XLSX, import review, plan/complete/persist, zero-diff re-import, desktop/mobile, offline reload and editing, no page errors.');
}finally{await browser.close();}
