import {native,permission,syncNotifications,notificationStatus,exactSettings,onNativeResume,onNotificationAction} from './platform/notifications.js';
import {PUBLIC_URL,loadCatalog,sourceCandidate,sourceState,selectedUpdate,reconcileIds} from './sources.js';
import {addDays,academicWeek,monday,nowInZone,clock,minute,validDate} from './domain/dates.js';
import {dayEvents,occurrences,overlaps,DEFAULT_TERM,BELLS} from './domain/schedule.js';
import {freeWindows,recommend,planSession,completeTask,finishSession,catchUp,unallocated} from './domain/planner.js';
import {readXlsx} from './import/xlsx.js';
import {inferMipt,importDiff,applyOverrides} from './import/mipt.js';
import {loadState,saveState,newState,validateBackup,migrateState} from './storage.js';

const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={today:'◫',week:'▦',tasks:'☑',more:'☷'};
const labels={today:'Сегодня',week:'Неделя',tasks:'Задачи',more:'Ещё'};
const kinds={lecture:'Лекция',seminar:'Семинар',lab:'Практикум',sport:'Спорт',practice:'Практическое',other:'Занятие',work:'Работа над задачей'};
const shortDays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const now=()=>nowInZone(state?.schedule?.institution.timezone||'Europe/Moscow');
const formatDate=(d,options={day:'numeric',month:'long'})=>new Intl.DateTimeFormat('ru-RU',{...options,timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const duration=m=>m>=60?`${Math.floor(m/60)} ч${m%60?' '+m%60+' мин':''}`:`${m} мин`;
let state,storageError='';
try{state=loadState(nowInZone().date);}catch(e){state=newState(nowInZone().date);storageError=e.message;}
let view=new URLSearchParams(location.search).get('view')==='tasks'?'tasks':'today',date=validDate(new URLSearchParams(location.search).get('date'))?new URLSearchParams(location.search).get('date'):now().date,weekMode='actual',candidate=null,recommendIndex={},taskFilter='open';
const sourceBase=native?PUBLIC_URL:new URL('./',document.baseURI).href;
let sourceCatalog=null,updateCandidate=null,updateCount=0,sourceMessage='';
function persist(){if(storageError)throw Error('Сохранение отключено: сначала сохраните исходные данные и восстановите хранилище.');saveState(state);syncNotifications(state);}
function mutate(fn){const previous=structuredClone(state);try{fn();persist();render();}catch(e){state=previous;toast(e.message);}}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),4500);}
function modal(title,content){dialog.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button class="icon-button" data-action="close" aria-label="Закрыть">×</button></div>${content}`;if(!dialog.open)dialog.showModal();}
function nav(){return Object.keys(labels).map(key=>`<button data-nav="${key}" class="nav-item ${view===key?'active':''}" ${view===key?'aria-current="page"':''}><span aria-hidden="true">${icons[key]}</span>${labels[key]}</button>`).join('');}
function render(){
  const term=state.schedule?.term||DEFAULT_TERM,aw=academicWeek(date,term);
  app.innerHTML=`<aside class="sidebar"><a href="./" class="brand"><span class="brand-mark">▦</span>сетка<span class="brand-dot">.</span></a><div class="workspace-label">ЛИЧНЫЙ УЧЕБНЫЙ ПЛАН</div><nav>${nav()}</nav><div class="sidebar-bottom"><div class="term-label">${esc(term.title)}</div><strong>${esc(state.groupId)}</strong><p>МФТИ · Москва</p><span class="local-state"><i></i> На этом устройстве</span></div></aside><div class="shell"><header class="topbar"><span>МФТИ <span class="divider">/</span> ${esc(state.groupId)}</span><span class="desktop-note">${esc(term.title)} <span class="divider">/</span> ${aw.number>0?'Неделя '+aw.number:'Вне семестра'}</span><button class="subtle" data-action="add-task">＋ Задача</button></header><main>${updateCandidate&&view!=='more'?'<div class="notice"><strong>Обновление расписания</strong> · '+updateCount+' изменений <button class="subtle" data-action="review-update">Просмотреть изменения</button></div>':''}${storageError?`<div class="notice error">${esc(storageError)} Данные не перезаписываются. <button data-action="raw-backup">Скачать исходные данные</button></div>`:''}${view==='today'?today():view==='week'?week():view==='tasks'?tasks():more()}</main><footer class="page-footer">Сетка · время для учёбы и всего остального<span>Europe/Moscow</span></footer></div><nav class="mobile-nav">${nav()}</nav>`;
}
function dateNav(){return `<div class="date-control"><button class="icon-button" data-action="prev" aria-label="Предыдущий ${view==='week'?'неделя':'день'}">‹</button><input aria-label="Дата расписания" type="date" id="day-picker" value="${date}"><button class="icon-button" data-action="next" aria-label="Следующий день">›</button><button class="subtle" data-action="today">Сегодня</button></div>`;}
function windowsForDay(events){const n=now();if(date<n.date)return [];return freeWindows(events,Math.max(state.settings.dayStart,date===n.date?n.minute:0),state.settings.dayEnd);}
function today(){
  const n=now(),events=dayEvents(state,date),windows=windowsForDay(events),week=academicWeek(date,state.schedule?.term||DEFAULT_TERM);
  const current=date===n.date?events.find(e=>e.start<=n.minute && e.end>n.minute):null;
  const next=events.find(e=>date>n.date || (date===n.date && e.start>n.minute));
  const free=windows.reduce((a,w)=>a+w.end-w.start,0),pending=state.tasks.filter(t=>t.status==='todo');
  const timeline=[...events,...windows.map(w=>({...w,type:'free'}))].sort((a,b)=>a.start-b.start);
  return `<div class="page-heading"><div><div class="eyebrow">${formatDate(date,{weekday:'long'}).toLocaleUpperCase('ru')} · ${week.parity==='odd'?'НЕЧЁТНАЯ':'ЧЁТНАЯ'} НЕДЕЛЯ</div><h1>${date===n.date?'Сегодня':formatDate(date)}</h1><p>${date===n.date?formatDate(date)+' · ':''}Учёба по расписанию. Остальное — по вам.</p></div>${dateNav()}</div>
  ${!state.schedule?`<div class="setup-banner"><div><strong>Начните со своего расписания</strong><p>Выберите программу и курс. Сетка найдёт книгу и предложит проверить занятия.</p></div><button class="primary" data-action="catalog">Выбрать расписание МФТИ <span>↗</span></button></div>`:''}
  <div class="today-layout"><section class="day-column"><div class="now-panel"><div class="now-top"><span class="live-dot"></span><span>${date===n.date?'СЕЙЧАС · '+clock(n.minute):date<n.date?'ДЕНЬ ЗАВЕРШЁН':'ПЛАН НА ДЕНЬ'}</span><span class="now-symbol">↗</span></div><h2>${current?esc(current.title):date<n.date?'Всё осталось в истории':windows.length?'Время в вашем распоряжении':'На сегодня всё'}</h2><p>${current?`${clock(current.start)}–${clock(current.end)} · ${esc(current.location||kinds[current.kind]||'Личное событие')}`:windows.length?`Ближайшее окно: ${clock(windows[0].start)}–${clock(windows[0].end)}`:'Можно отдохнуть и посмотреть следующий день.'}</p><div class="next-line"><span>ДАЛЬШЕ</span>${next?`<strong>${clock(next.start)}</strong> ${esc(next.title)}`:`<span>${events.length?'Больше событий нет':'Нет запланированных событий'}</span>`}</div></div>
  <div class="section-heading"><h2>Ход дня</h2><button class="subtle" data-action="add-event">＋ Событие</button></div>
  ${overlaps(events).length?'<div class="notice warning">Есть пересечения. Проверьте варианты занятий и запланированные сессии.</div>':''}
  <div class="timeline">${timeline.length?timeline.map(e=>e.type==='free'?freeCard(e):eventCard(e,n)).join(''):'<div class="empty">Здесь пока свободно. Добавьте расписание или личное событие.</div>'}</div></section>
  <aside class="day-aside"><div class="summary-strip"><div><strong>${duration(free)}</strong><span>свободно${date===n.date?' впереди':''}</span></div><div><strong>${events.filter(e=>e.type==='lesson').length}</strong><span>занятий</span></div></div><section class="aside-section"><div class="section-heading"><h2>На очереди</h2><span class="count">${pending.length}</span></div><p class="section-caption">Задачи ещё не занимают время.</p>${pending.slice(0,4).map(t=>taskRow(t,true)).join('')||'<div class="empty small">Спокойный список.<br>Добавьте то, что нужно сделать.</div>'}<button class="text-link" data-nav="tasks">Все задачи <span>↗</span></button></section><div class="quiet-note"><span>◷</span><p>Между парами есть жизнь.<br>Планируйте только то, что помещается.</p></div></aside></div>`;
}
function eventCard(e,n){const past=date<n.date || date===n.date && e.end<=n.minute;const active=date===n.date && e.start<=n.minute && e.end>n.minute;return `<div class="timeline-row ${past?'past':''}"><div class="time-label"><strong>${clock(e.start)}</strong><span>${clock(e.end)}</span></div><button class="event-card ${e.kind==='sport'?'sport':e.type==='session'?'work':''} ${active?'current':''}" data-action="event-detail" data-id="${esc(e.id)}"><div class="card-meta">${e.type==='session'?'ЗАПЛАНИРОВАНО':e.type==='personal'?'ЛИЧНОЕ':esc(kinds[e.kind])}${e.time?.slotNumbers.length?' · '+e.time.slotNumbers.join('–')+' ПАРА':''}${active?' · СЕЙЧАС':''}${e.status==='done'?' · ГОТОВО':''}</div><h3>${esc(e.title)}</h3><p>${esc(e.location|| (e.type==='session'?duration(e.end-e.start):'Место не указано'))}${e.instructors?.length?' · '+esc(e.instructors.join(', ')):''}</p>${e.recurrence?.parity!=='all' && e.recurrence?`<span class="tiny-tag">${e.recurrence.parity==='odd'?'Нечётные':'Чётные'} недели</span>`:''}</button></div>`;}
function freeCard(w){
  const options=recommend(state.tasks,state.sessions,w,date),key=`${date}:${w.start}`,rec=options[(recommendIndex[key]||0)%Math.max(1,options.length)];
  return `<div class="timeline-row"><div class="time-label free-time"><strong>${clock(w.start)}</strong><span>${clock(w.end)}</span></div><div class="free-card"><div class="free-label"><span>СВОБОДНО</span><strong>${duration(w.end-w.start)}</strong></div>${rec?`<div class="recommendation"><div class="card-meta">МОЖНО УСПЕТЬ</div><h3>${esc(rec.task.title)}</h3><p>${esc(rec.reason)}</p><div class="recommend-actions"><button class="primary small" data-action="plan" data-task="${esc(rec.task.id)}" data-start="${w.start}" data-duration="${rec.duration}">Запланировать ${duration(rec.duration)} <span>↗</span></button>${options.length>1?`<button class="subtle" data-action="another" data-key="${key}">Другое</button>`:''}</div></div>`:`<p class="free-hint">${state.tasks.some(t=>t.status==='todo')?'Нет подходящей незапланированной задачи. Можно оставить окно свободным.':'Прогулка, обед или время для себя.'}</p>`}</div></div>`;
}
function taskRow(t,compact=false){return `<div class="task-row"><button class="check ${t.status==='done'?'checked':''}" ${t.status==='done'?'disabled':''} data-action="complete-task" data-id="${esc(t.id)}" aria-label="Выполнить: ${esc(t.title)}">${t.status==='done'?'✓':''}</button><div><strong>${esc(t.title)}</strong><p>${duration(t.remainingMinutes)}${t.dueOn?' · до '+formatDate(t.dueOn):''}${t.origin?' · '+formatDate(t.origin.date)+' · '+esc(t.origin.startsAt):t.occurrenceId?' · после занятия':''}</p>${t.origin?`<button class="origin-link" data-action="task-origin" data-id="${esc(t.id)}">${esc(kinds[t.origin.kind])} · ${formatDate(t.origin.date)} · ${esc(t.origin.startsAt)} ↗</button>`:''}${!compact && t.status==='todo'?`<span class="task-meta">Приоритет ${t.priority}/5 · ${t.splittable?'можно по частям':'целиком'} · ${duration(unallocated(t,state.sessions))} не запланировано</span>`:''}</div>${!compact && t.status==='todo'?`<button class="subtle" data-action="manual-plan" data-id="${esc(t.id)}">План</button>`:''}</div>`;}
function tasks(){const list=state.tasks.filter(t=>taskFilter==='done'?t.status==='done':t.status==='todo');return `<div class="page-heading"><div><div class="eyebrow">УЧЕБНОЕ И ЛИЧНОЕ</div><h1>Задачи</h1><p>Сначала что сделать. Затем — когда.</p></div><button class="primary" data-action="add-task">＋ Новая задача</button></div><div class="segmented"><button data-filter="open" class="${taskFilter==='open'?'selected':''}">В работе</button><button data-filter="done" class="${taskFilter==='done'?'selected':''}">Завершённые</button></div><section class="task-list">${list.map(t=>taskRow(t)).join('')||'<div class="empty">Здесь пока нет задач.</div>'}</section>`;}
function gridLanes(events){
  const ends=[],placed=[];
  for(const event of [...events].sort((a,b)=>minute(a.time.startsAt)-minute(b.time.startsAt))){
    const slots=event.time.slotNumbers;if(!slots.length)continue;
    const start=Math.min(...slots),end=Math.max(...slots);let lane=ends.findIndex(e=>e<start);
    if(lane<0)lane=ends.length;ends[lane]=end;placed.push({event,lane});
  }
  return placed.map(p=>({...p,lanes:ends.length}));
}
function week(){
  const start=monday(date),schedule=state.schedule;
  const ds=Array.from({length:6},(_,i)=>addDays(start,i));
  const events=ds.map(d=>weekMode==='actual'?occurrences(schedule,state.groupId,d):(schedule?.series||[]).filter(s=>s.cohorts.some(c=>c.groupId===state.groupId)&&s.recurrence.weekdays.includes(ds.indexOf(d)+1)&&(s.recurrence.parity==='all'||s.recurrence.parity===weekMode)).map(s=>({...s,id:s.id,seriesId:s.id})));
  return `<div class="page-heading"><div><div class="eyebrow">АКАДЕМИЧЕСКАЯ СЕТКА</div><h1>Неделя</h1><p>${formatDate(start)} — ${formatDate(addDays(start,5))}</p></div>${dateNav()}</div><div class="week-toolbar"><div class="segmented">${[['actual','По датам'],['odd','Нечётная'],['even','Чётная']].map(([v,l])=>`<button data-week="${v}" class="${weekMode===v?'selected':''}">${l}</button>`).join('')}</div><span class="section-caption">МФТИ · 7 пар · Москва</span></div><div class="grid-scroll"><div class="week-grid"><div class="grid-corner">ПАРА</div>${ds.map((d,i)=>`<button class="grid-day ${d===now().date?'is-today':''}" style="grid-column:${i+2}" data-day="${d}">${shortDays[i]} <strong>${formatDate(d,{day:'numeric'})}</strong></button>`).join('')}${(schedule?.bellSchedule||BELLS).slots.map((s,i)=>`<div class="grid-slot" style="grid-row:${i+2};grid-column:1"><b>${s.number}</b><span>${s.startsAt}<br>${s.endsAt}</span></div>${ds.map((_,di)=>`<div class="grid-cell" style="grid-row:${i+2};grid-column:${di+2}"></div>`).join('')}`).join('')}${events.map((es,di)=>gridLanes(es).map(({event:e,lane,lanes})=>{const slots=e.time.slotNumbers;if(!slots.length)return '';return `<button class="grid-lesson ${e.kind==='sport'?'sport':''}" style="grid-row:${Math.min(...slots)+1} / ${Math.max(...slots)+2};grid-column:${di+2};width:calc((100% - 8px) / ${lanes});margin-left:calc(4px + (100% - 8px) * ${lane} / ${lanes})" data-action="series-detail" data-id="${esc(e.seriesId)}"><span>${esc(kinds[e.kind])}</span><strong>${esc(e.title)}</strong><small>${esc(e.location||'Место не указано')}</small>${e.cohorts.find(c=>c.groupId===state.groupId)?.variant?'<small>Вариант '+esc(e.cohorts.find(c=>c.groupId===state.groupId).variant)+'</small>':''}${e.recurrence.parity!=='all'?`<small>${e.recurrence.parity==='odd'?'неч.':'чёт.'}</small>`:''}</button>`;}).join('')).join('')}</div></div><p class="section-caption">${weekMode==='actual'?'Личные события и рабочие сессии смотрите в выбранном дне.':'Шаблон повторения: без привязки к датам семестра.'} Нажмите на день, чтобы открыть его.</p>`;
}
function more(){return `<div class="page-heading"><div><div class="eyebrow">ВАША СЕТКА</div><h1>Расписание и настройки</h1><p>Данные хранятся в этом браузере.</p></div></div><div class="settings-grid"><section class="settings-panel"><h2>Расписание МФТИ</h2>${sourcePanel()}<p>${state.schedule?esc(state.schedule.importMeta.workbook)+' · '+state.schedule.series.length+' записей':'Расписание ещё не добавлено'}</p><label class="file-button primary">Импортировать .xlsx<input id="xlsx-file" type="file" accept=".xlsx"></label><p class="section-caption">Файл обрабатывается на устройстве. Старый формат .xls пока не поддерживается.</p><button class="text-link" data-action="export-schedule" ${!state.schedule?'disabled':''}>Скачать канонический JSON ↗</button></section><section class="settings-panel"><h2>Время для планирования</h2><form id="bounds-form"><div class="form-row"><label>Начало<input name="start" type="time" value="${clock(state.settings.dayStart)}" required></label><label>Конец<input name="end" type="time" value="${clock(state.settings.dayEnd)}" required></label></div><button class="secondary" type="submit">Сохранить границы дня</button></form><p class="section-caption">Окна от 20 минут. Время расписания всегда московское.</p></section><section class="settings-panel"><h2>После занятий</h2><p>Новые задачи появляются после завершения занятия, в том числе при следующем запуске.</p>${state.rules.map(r=>`<label class="rule-row"><input type="checkbox" data-rule="${r.id}" ${r.enabled?'checked':''}><span><strong>${kinds[r.kind]}</strong><small>${esc(r.title)} · ${duration(r.minutes)}</small></span><button type="button" class="subtle" data-action="edit-rule" data-id="${r.id}">Изменить</button></label>`).join('')}<p class="section-caption">Для занятий без явного типа правила не срабатывают. Тип можно уточнить в карточке занятия. Спорт не создаёт задач.</p></section>${notificationPanel()}<section class="settings-panel"><h2>Данные и приложение</h2><button class="secondary" data-action="export-backup">Скачать резервную копию</button><label class="file-button secondary">Восстановить копию<input id="backup-file" type="file" accept=".json"></label><button class="text-link" data-action="semester">Обзор семестра ↗</button><p class="section-caption" id="offline-status">${navigator.serviceWorker?.controller?'Приложение доступно офлайн.':'Офлайн-копия готовится после первого открытия.'}</p><p class="section-caption">На iPhone: Safari → Поделиться → На экран «Домой». Для установки с телефона нужен HTTPS. Локальный HTTP подходит для предварительного просмотра.</p><p class="section-caption">Данные не синхронизируются между устройствами.</p></section></div>`;}

function taskForm(){modal('Новая задача',`<form id="task-form"><label>Что нужно сделать?<input name="title" required maxlength="180" placeholder="Например, решить задачи по физике" autofocus></label><div class="form-row"><label>Осталось, мин<input name="minutes" type="number" min="5" max="10000" step="5" value="45" required></label><label>Срок<input name="due" type="date"></label></div><div class="form-row"><label>Приоритет<select name="priority">${[1,2,3,4,5].map(n=>`<option ${n===3?'selected':''}>${n}</option>`).join('')}</select></label><label class="checkbox-label"><input name="split" type="checkbox" checked>Можно по частям</label></div><button class="primary full">Добавить задачу</button></form>`);}
function planForm(taskId,start,dur){const task=state.tasks.find(t=>t.id===taskId);if(!task)return;const n=now();modal('Время для задачи',`<form id="plan-form" data-task="${esc(taskId)}"><p class="plan-title">${esc(task.title)}</p><label>Дата<input name="date" type="date" required min="${n.date}" value="${date<n.date?n.date:date}"></label><div class="form-row"><label>Начало<input name="start" type="time" required value="${clock(start??Math.max(state.settings.dayStart,n.minute))}"></label><label>Длительность, мин<input name="duration" type="number" min="1" max="${unallocated(task,state.sessions)}" value="${dur??Math.min(45,unallocated(task,state.sessions))}" required></label></div><p class="section-caption">Проверим пересечения и уже запланированную работу перед сохранением.</p><button class="primary full">Подтвердить время</button></form>`);}
function detail(id,isSeries=false){const e=isSeries?state.schedule?.series.find(s=>s.id===id):dayEvents(state,date).find(e=>e.id===id);if(!e)return;
  modal(e.title,`<p>${e.time?e.time.startsAt+'–'+e.time.endsAt:clock(e.start)+'–'+clock(e.end)} · ${esc(e.location||kinds[e.kind]||'Личное событие')}</p>${e.source?`<label>Тип занятия<select id="lesson-kind" data-id="${esc(e.seriesId||e.id)}">${Object.entries(kinds).filter(([k])=>k!=='work').map(([k,l])=>`<option value="${k}" ${e.kind===k?'selected':''}>${l}</option>`).join('')}</select></label><div class="source-box"><div class="eyebrow">ИСТОЧНИК</div><p>${esc(e.source.workbook)}<br>${esc(e.source.sheet)} · ${esc(e.source.ranges.join(', '))}</p><blockquote>${esc(e.source.rawText)}</blockquote>${e.confidence.warnings.map(w=>`<p class="source-warning">${esc(w)}</p>`).join('')}</div>`:''}${e.type==='session'&&e.status==='planned'?`<button class="primary full" data-action="finish-session" data-id="${esc(e.id)}">Сессия выполнена</button><button class="subtle full" data-action="skip-session" data-id="${esc(e.id)}">Убрать из плана</button>`:''}${e.type==='personal'?`<button class="secondary" data-action="delete-event" data-id="${esc(e.id)}">Удалить событие</button>`:''}`);
}
async function openWorkbook(file){toast('Читаем структуру книги…');try{const ir=await readXlsx(await file.arrayBuffer(),file.name);candidate=applyOverrides(inferMipt(ir),state.overrides);reviewImport();}catch(e){toast(e.message);}}
async function fixture(){try{const response=await fetch('./fixtures/mipt/File.xlsx');if(!response.ok)throw Error('Приложенная книга недоступна. Выберите локальный файл.');await openWorkbook(new File([await response.blob()],'File.xlsx'));}catch(e){toast(e.message);}}
function reviewImport(group=state.groupId){if(!candidate.groups.some(g=>g.id===group))group=candidate.groups[0].id;const records=candidate.series.filter(s=>s.cohorts.some(c=>c.groupId===group));
  modal('Проверка расписания',`<form id="import-form"><div class="notice">${candidate.groups.length} групп · ${candidate.importMeta.blocks.length} блоков. Проверьте даты семестра: конец 31 декабря — предварительная граница.</div><label>Ваша группа<select id="import-group" name="group">${candidate.groups.map(g=>`<option ${g.id===group?'selected':''}>${esc(g.id)}</option>`).join('')}</select></label><div class="form-row"><label>Начало семестра<input name="from" type="date" value="${candidate.term.startsOn}" required></label><label>Конец семестра<input name="to" type="date" value="${candidate.term.endsOn}" required></label></div><label>Дата в первой нечётной неделе<input name="anchor" type="date" value="${candidate.term.parityAnchor.date}" required></label><p class="section-caption">${records.length} записей. Неоднозначные варианты выключены: включите только свои. Неопределённый тип остаётся «Занятием» и не создаёт заданий.</p><div class="import-records">${records.map(s=>`<label class="import-record"><input type="checkbox" name="record" value="${s.id}" ${s.blocked?'disabled':state.schedule?.importMeta.excluded?.includes(s.source.fingerprint)?'':!s.needsChoice||state.schedule?.series.some(o=>o.source.fingerprint===s.source.fingerprint)?'checked':''}><span><strong>${esc(s.title)}</strong><small>${shortDays[s.recurrence.weekdays[0]-1]} · ${s.time.startsAt}–${s.time.endsAt} · ${esc(s.location)} · ${s.recurrence.parity==='all'?'каждую неделю':s.recurrence.parity==='odd'?'нечётные':'чётные'}</small><small>${esc(s.source.ranges.join(', '))}${s.cohorts.find(c=>c.groupId===group)?.variant?' · вариант '+esc(s.cohorts.find(c=>c.groupId===group).variant):''}</small><details><summary>Исходный текст${s.confidence.warnings.length?' · проверить':''}</summary><span>${esc(s.source.rawText)}</span>${s.confidence.warnings.map(w=>`<small class="source-warning">${esc(w)}</small>`).join('')}</details></span></label>`).join('')}</div><button class="primary full sticky-button">Просмотреть изменения</button></form>`);
}
function download(data,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function semester(){const t=state.schedule?.term||DEFAULT_TERM;let dates=[];for(let d=monday(t.startsOn);d<=t.endsOn;d=addDays(d,7))dates.push(d);modal('Семестр',`<p>${esc(t.title)} · ${formatDate(t.startsOn)}–${formatDate(t.endsOn)}</p><div class="semester-grid">${dates.map(d=>{const w=academicWeek(d,t);return `<button data-day="${d}"><b>${w.number}</b><span>${formatDate(d)}</span><small>${w.parity==='odd'?'нечётная':'чётная'}</small></button>`;}).join('')}</div>`);}

document.addEventListener('click',async event=>{
  const b=event.target.closest('button,a[data-action]');if(!b)return;
  if(b.dataset.nav){view=b.dataset.nav;render();window.scrollTo(0,0);return;}
  if(b.dataset.day){date=b.dataset.day;view='today';dialog.close();render();return;}
  if(b.dataset.week){weekMode=b.dataset.week;render();return;}
  if(b.dataset.filter){taskFilter=b.dataset.filter;render();return;}
  const a=b.dataset.action,id=b.dataset.id;
  if(a==='close')dialog.close();
  if(a==='catalog')await showCatalog();
  if(a==='check-source')await checkSource(true);
  if(a==='review-update'&&updateCandidate){candidate=updateCandidate;reviewImport();}
  if(a==='notification-permission'){const result=await permission(true);mutate(()=>state.notifications.enabled=result==='granted');toast(result==='granted'?'Уведомления включены':'Разрешение не получено');}
  if(a==='exact-settings')await exactSettings();
  if(a==='task-origin'){const t=state.tasks.find(t=>t.id===id);if(t?.origin)modal('Занятие, из которого появилась задача',`<p>${esc(t.origin.subject)}</p><p>${formatDate(t.origin.date)} · ${esc(t.origin.startsAt)}–${esc(t.origin.endsAt)} · ${esc(kinds[t.origin.kind])}</p><p>${esc(t.origin.source?.rawText||'')}</p><button class="primary full" data-day="${t.origin.date}">Открыть день</button>`);}
  if(a==='today'){date=now().date;render();}
  if(a==='prev'||a==='next'){date=addDays(date,(a==='prev'?-1:1)*(view==='week'?7:1));render();}
  if(a==='add-task')taskForm();
  if(a==='fixture')await fixture();
  if(a==='plan')planForm(b.dataset.task,Number(b.dataset.start),Number(b.dataset.duration));
  if(a==='manual-plan')planForm(id);
  if(a==='another'){recommendIndex[b.dataset.key]=(recommendIndex[b.dataset.key]||0)+1;render();}
  if(a==='complete-task')mutate(()=>completeTask(state,id));
  if(a==='event-detail')detail(id);
  if(a==='series-detail')detail(id,true);
  if(a==='finish-session'){mutate(()=>finishSession(state,id));dialog.close();}
  if(a==='skip-session'){mutate(()=>state.sessions.find(s=>s.id===id).status='skipped');dialog.close();}
  if(a==='delete-event'){mutate(()=>state.events=state.events.filter(e=>e.id!==id));dialog.close();}
  if(a==='export-schedule')download(state.schedule,'setka-schedule.json');
  if(a==='export-backup')download(state,'setka-backup.json');
  if(a==='raw-backup')download(localStorage.getItem('setka.v1')||'','setka-original-data.json');
  if(a==='semester')semester();
  if(a==='add-event')modal('Личное событие',`<form id="event-form"><label>Название<input name="title" maxlength="180" required autofocus></label><label>Дата<input name="date" type="date" value="${date}" required></label><div class="form-row"><label>Начало<input name="start" type="time" required></label><label>Конец<input name="end" type="time" required></label></div><label>Место<input name="location" maxlength="100"></label><button class="primary full">Добавить событие</button></form>`);
  if(a==='edit-rule'){const r=state.rules.find(r=>r.id===id);modal('Правило после занятия',`<form id="rule-form" data-id="${id}"><label>Название задачи<input name="title" value="${esc(r.title)}" maxlength="100" required></label><label>Оценка, мин<input name="minutes" type="number" value="${r.minutes}" min="5" max="600" required></label><button class="primary full">Сохранить правило</button></form>`);}
});
document.addEventListener('change',async event=>{const el=event.target;
  if(el.id==='day-picker'&&validDate(el.value)){date=el.value;render();}
  if(el.id==='xlsx-file'&&el.files[0])await openWorkbook(el.files[0]);
  if(el.id==='import-group')reviewImport(el.value);
  if(el.dataset.rule)mutate(()=>{catchUp(state,now());state.rules.find(r=>r.id===el.dataset.rule).enabled=el.checked;});
  if(el.id==='lesson-kind')mutate(()=>{catchUp(state,now());const series=state.schedule.series.find(s=>s.id===el.dataset.id);series.kind=el.value;state.overrides??={};state.overrides[series.source.fingerprint]={kind:el.value,rawText:series.source.rawText};});
  if(el.id==='backup-file'&&el.files[0]){try{const restored=JSON.parse(await el.files[0].text());migrateState(restored);validateBackup(restored);modal('Восстановить резервную копию?',`<p>Будут заменены текущие данные: ${restored.tasks.length} задач, ${restored.sessions.length} сессий в копии.</p><button class="primary full" id="restore-confirm">Восстановить</button>`);document.querySelector('#restore-confirm').onclick=()=>{const old=state;state=restored;try{saveState(state);storageError='';dialog.close();render();toast('Копия восстановлена');}catch(e){state=old;toast(e.message);}};}catch(e){toast('Не удалось восстановить: '+e.message);}}
});
document.addEventListener('submit',event=>{event.preventDefault();const f=event.target,v=new FormData(f);
  try{
    if(f.id==='notification-form')mutate(()=>{state.notifications={...state.notifications,enabled:v.has('enabled'),lessons:v.has('lessons'),sessions:v.has('sessions'),followups:v.has('followups'),lessonLead:Number(v.get('lessonLead')),sessionLead:Number(v.get('sessionLead')),quietStart:minute(v.get('quietStart')),quietEnd:minute(v.get('quietEnd'))};toast('Настройки уведомлений сохранены');});
    if(f.id==='task-form')mutate(()=>{const title=v.get('title').trim();if(!title)throw Error('Введите название задачи.');state.tasks.push({id:crypto.randomUUID(),title,estimatedMinutes:Number(v.get('minutes')),remainingMinutes:Number(v.get('minutes')),priority:Number(v.get('priority')),dueOn:v.get('due')||null,splittable:v.has('split'),minimumSessionMinutes:20,status:'todo'});dialog.close();});
    if(f.id==='plan-form'){const d=v.get('date');mutate(()=>{planSession(state,f.dataset.task,d,minute(v.get('start')),Number(v.get('duration')),now());date=d;view='today';dialog.close();toast('Время запланировано');});}
    if(f.id==='bounds-form')mutate(()=>{const start=minute(v.get('start')),end=minute(v.get('end'));if(end<=start)throw Error('Конец дня должен быть позже начала.');state.settings={...state.settings,dayStart:start,dayEnd:end};toast('Границы сохранены');});
    if(f.id==='event-form')mutate(()=>{const start=minute(v.get('start')),end=minute(v.get('end')),d=v.get('date'),title=v.get('title').trim();if(!title||end<=start)throw Error('Проверьте название и время.');if(dayEvents(state,d).some(e=>e.start<end&&e.end>start))throw Error('Это время уже занято. Выберите другой интервал.');state.events.push({id:crypto.randomUUID(),date:d,start,end,title,location:v.get('location')});dialog.close();});
    if(f.id==='rule-form')mutate(()=>{const r=state.rules.find(r=>r.id===f.dataset.id);r.title=v.get('title').trim();r.minutes=Number(v.get('minutes'));if(!r.title)throw Error('Введите название.');dialog.close();});
    if(f.id==='import-form'){
      if(v.get('to')<v.get('from'))throw Error('Проверьте границы семестра.');
      const selected=new Set(v.getAll('record'));if(!selected.size)throw Error('Выберите хотя бы одно занятие.');
      const next=structuredClone(candidate),group=v.get('group');next.importMeta.excluded=next.series.filter(s=>s.cohorts.some(c=>c.groupId===group)&&!selected.has(s.id)).map(s=>s.source.fingerprint);next.series=next.series.filter(s=>selected.has(s.id)&&!s.blocked);
      next.term={...next.term,startsOn:v.get('from'),endsOn:v.get('to'),parityAnchor:{date:v.get('anchor'),parity:'odd'}};
      next.series.forEach(s=>{s.recurrence.validFrom=next.term.startsOn;s.recurrence.validTo=next.term.endsOn;});
      const diff=importDiff(state.schedule,next),changed=diff.filter(d=>d.type!=='unchanged');
      modal('Применить расписание?',`<p>${esc(group)} · ${next.series.length} записей. Личные задачи и сессии сохранятся. Пересечения после обновления будут показаны в дне.</p><div class="diff-list">${changed.length?changed.map(d=>`<p><span class="diff-tag">${{added:'Добавлено',removed:'Удалено',changed:'Изменено'}[d.type]}</span> ${esc((d.after||d.before).title)}<small>${d.before?esc(d.before.time.startsAt+' · '+(d.before.location||'без места'))+' → ':''}${d.after?esc(d.after.time.startsAt+' · '+(d.after.location||'без места')):''}</small></p>`).join(''):'<p>Расписание не изменилось.</p>'}</div><button class="primary full" id="apply-import">Применить расписание</button>`);
      document.querySelector('#apply-import').onclick=()=>mutate(()=>{catchUp(state,now());state.schedule=reconcileIds(state.schedule,next);state.groupId=group;updateCandidate=null;updateCount=0;state.generatedThrough=now();dialog.close();view='today';toast('Расписание добавлено');});
    }
  }catch(e){toast(e.message);}
});

if(!storageError){try{catchUp(state,now());persist();}catch(e){storageError=e.message;}}
render();
setInterval(()=>{if(document.hidden||dialog.open)return;mutate(()=>catchUp(state,now()));},60000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!dialog.open)mutate(()=>catchUp(state,now()));});
if(!native && 'serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('Офлайн-копия недоступна. Для телефона нужен HTTPS.'));

function sourcePanel(){
  const source=sourceCatalog?.sources.find(s=>s.id===state.schedule?.importMeta.source?.id);
  const checked=source?.checkedAt||state.schedule?.importMeta.source?.checkedAt;
  const label=state.schedule?.importMeta.source?.label;
  return `<div class="source-status"><strong>${esc(label||'Источник ещё не выбран')}</strong><p>${esc(sourceMessage||(label?'Проверка при подключении к сети':'Автоматически находить и проверять книгу МФТИ'))}</p>${checked?'<small>МФТИ проверен: '+new Date(checked).toLocaleString('ru-RU')+'</small>':''}${updateCandidate?'<p>'+updateCount+' изменений в расписании группы</p><button class="primary full" data-action="review-update">Просмотреть изменения</button>':''}<button class="secondary" data-action="catalog">Выбрать программу / курс</button>${label?'<button class="subtle" data-action="check-source">Проверить обновления</button>':''}</div>`;
}
async function showCatalog(){
  try{sourceCatalog=await loadCatalog(sourceBase);}
  catch(e){toast(e.message);if(!sourceCatalog)return;}
  modal('Расписание МФТИ',`<p>Выберите программу и курс. После загрузки проверим группу и изменения.</p><div class="catalog-list">${sourceCatalog.sources.map(s=>`<button class="catalog-item" data-source="${s.id}" ${!s.supported||s.status!=='ok'?'disabled':''}><strong>${esc(s.label)}</strong><small>${esc(s.academicYear)} · ${s.term==='autumn'?'Осень':'Весна'}${s.school?' · '+esc(s.school):''}</small><small>${s.status!=='ok'?'Источник временно недоступен':s.supported?'Открыть и выбрать группу':'Формат .xls пока не поддерживается'}</small></button>`).join('')}</div>`);
  dialog.querySelectorAll('[data-source]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{candidate=await sourceCandidate(sourceCatalog.sources.find(s=>s.id===button.dataset.source),sourceBase,state);reviewImport();}catch(e){button.disabled=false;toast(e.message);}});
}
async function checkSource(manual=false){
  if(!state.schedule?.importMeta.source)return;
  try{
    sourceCatalog=await loadCatalog(sourceBase);const source=sourceCatalog.sources.find(s=>s.id===state.schedule.importMeta.source.id),status=sourceState(state.schedule,source);
    if(status==='current'){updateCandidate=null;sourceMessage='✓ Актуально по последней проверке МФТИ';}
    else if(status==='update'){updateCandidate=await sourceCandidate(source,sourceBase,state);updateCount=importDiff(state.schedule,selectedUpdate(updateCandidate,state)).filter(d=>d.type!=='unchanged').length;sourceMessage='Доступна новая версия книги';}
    else sourceMessage=status==='missing'?'Источник исчез из каталога. Текущее расписание сохранено.':'Не удалось проверить МФТИ. Текущее расписание сохранено.';
  }catch(e){sourceMessage='Нет связи с каталогом. Сохранённое расписание доступно.';}
  if(!dialog.open)render();if(manual)toast(sourceMessage);
}
function notificationPanel(){const n=state.notifications;return `<section class="settings-panel"><h2>Уведомления</h2><p>${esc(notificationStatus())}</p><button class="secondary" data-action="notification-permission">Разрешить уведомления</button>${native?'<button class="subtle" data-action="exact-settings">Точное время на Android</button>':''}<form id="notification-form">${[['enabled','Включены'],['lessons','Перед занятиями'],['sessions','Перед рабочими сессиями'],['followups','Один итог после занятий']].map(([k,l])=>`<label class="rule-row"><input type="checkbox" name="${k}" ${n[k]?'checked':''}>${l}</label>`).join('')}<div class="form-row"><label>До занятия, мин<input name="lessonLead" type="number" min="0" max="60" value="${n.lessonLead}" required></label><label>До сессии, мин<input name="sessionLead" type="number" min="0" max="60" value="${n.sessionLead}" required></label></div><div class="form-row"><label>Тишина с<input name="quietStart" type="time" value="${clock(n.quietStart)}" required></label><label>До<input name="quietEnd" type="time" value="${clock(n.quietEnd)}" required></label></div><button class="secondary">Сохранить уведомления</button></form><p class="section-caption">${native?'Напоминания планируются системой на 30 дней вперёд и обновляются при открытии. После принудительной остановки приложения откройте Сетку снова.':'При закрытой PWA фоновые напоминания не гарантируются. Сервер Web Push не подключён; на Android используйте APK для фоновых уведомлений.'}</p></section>`;}
checkSource();
window.addEventListener('online',()=>checkSource());
onNativeResume(()=>{mutate(()=>catchUp(state,now()));checkSource();});
onNotificationAction(data=>{if(data?.date&&validDate(data.date))date=data.date;view=data?.view==='tasks'?'tasks':'today';mutate(()=>catchUp(state,now()));});

setInterval(()=>checkSource(),30*60*1000);
