import {loadCatalog,sourceCandidate} from './sources.js';
import {importDiff} from './import/mipt.js';
import {addPersonalSelection,updatePersonalSource} from './domain/individual-plan.js';
import {subjectKey} from './domain/study.js';
import {validDate,weekday} from './domain/dates.js';
import {catchUp} from './domain/planner.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],kinds={lecture:'Лекции',seminar:'Семинары',practice:'Практикумы',lab:'Практикумы',class:'Занятия',other:'Неопределённый тип',sport:'Спорт'};
function reviewSeries(s){const r=s.recurrence;return `<p><strong>${esc(s.title)}</strong> · ${esc(kinds[s.kind])} · ${s.time.startsAt}–${s.time.endsAt} · ${esc(s.location||'')}<br>${r.weekdays.map(d=>days[d-1]).join(', ')} · ${esc(r.parity)} · ${r.validFrom} — ${r.validTo}<br>Только даты: ${r.datesOnly?'да':'нет'} · добавлены: ${esc(r.includeDates?.join(', ')||'—')} · исключены: ${esc(r.excludeDates?.join(', ')||'—')}<br>${esc(s.instructors?.join(', ')||'')} · ${esc(s.cohorts.map(c=>c.groupId).join(', '))}</p><blockquote>${esc(s.source.rawText)}</blockquote>`;}
export function individualNotice(state){return `${state.personalSelections?.some(s=>!s.disabled)?'<p class="notice">Индивидуальное расписание включено. '+(Object.values(state.academicSources||{}).some(s=>s.updateState==='update')?'Есть обновления выбранных источников. ':Object.values(state.academicSources||{}).some(s=>s.updateState==='unavailable')?'Не все источники удалось проверить. ':'')+'<button class="subtle" data-individual="manage">Мои выборы и источники</button></p>':''}${state.pendingAttendance?.length?'<p class="notice warning">Пересекающиеся занятия: автоматические задания ждут вашего выбора. <button class="subtle" data-individual="attendance">Где вы были?</button></p>':''}`;}
export function bindIndividualUI({getState,mutate,modal,base,toast,now}){
  let loaded=[],failures=[],loading=false;const updates=new Map();
  let checking=false;
  async function check(){
    if(checking||!Object.keys(getState().academicSources||{}).length)return;checking=true;
    try{
      const catalog=await loadCatalog(base),states={};
      for(const [id,source] of Object.entries(getState().academicSources||{})){
        const descriptor=catalog.sources.find(s=>s.id===id);
        if(!descriptor||descriptor.status!=='ok'){states[id]='unavailable';continue;}
        if(descriptor.sha256===source.schedule.importMeta.hash){states[id]='current';updates.delete(id);continue;}
        try{const candidate=await sourceCandidate(descriptor,base,{schedule:source.schedule,overrides:{}});updates.set(id,{candidate,diff:importDiff(source.schedule,candidate)});states[id]='update';}catch{states[id]='unavailable';}
      }
      mutate(()=>{for(const [id,status] of Object.entries(states))if(getState().academicSources[id])getState().academicSources[id].updateState=status;});
    }catch{mutate(()=>{for(const source of Object.values(getState().academicSources||{}))source.updateState='unavailable';});}
    finally{checking=false;}
  }
  setTimeout(check,3000);setInterval(check,30*60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check();});window.addEventListener('online',check);
  function choose(schedule,series,old=null){
    const state=getState(),own=(state.schedule?.series||[]).filter(s=>s.kind===series.kind&&subjectKey(s.title)===subjectKey(old?.subject||series.title));
    modal('Выбрать занятия',`<form id="individual-choice"><p>${esc(series.title)} · ${esc(kinds[series.kind])}<br>${esc(series.cohorts.map(c=>c.groupId).join(', '))} · ${series.time.startsAt}–${series.time.endsAt}<br>${esc(series.instructors?.join(', ')||'')}</p><label>Название предмета для группировки<input name="subject" value="${esc(old?.subject||series.title)}" required maxlength="180"></label><p class="section-caption">Можно исправить объединение разных предметов или дать одинаковое имя одному предмету. Исходное название сохранится ниже.</p><div class="form-row"><label>С<input name="from" type="date" value="${old?.from||schedule.term.startsOn}" required></label><label>До<input name="to" type="date" value="${old?.to||schedule.term.endsOn}" required></label></div><fieldset><legend>Дни выбранной серии</legend>${series.recurrence.weekdays.map(d=>`<label class="checkbox-label"><input type="checkbox" name="weekday" value="${d}" ${!old?.weekdays?.length||old.weekdays.includes(d)?'checked':''}>${days[d-1]}</label>`).join('')}</fieldset><label>Или только отдельные даты (через запятую, ГГГГ-ММ-ДД)<input name="dates" value="${old?.dates?.join(', ')||''}"></label><label>Пропустить отдельные даты (через запятую, ГГГГ-ММ-ДД)<input name="excludeDates" value="${old?.excludeDates?.join(', ')||''}"></label><p class="section-caption">Удалите дату из исключений, чтобы вернуть занятие. По умолчанию весь семестр. Выбор даты не создаёт занятие, которого нет в источнике.</p><fieldset><legend>Свои занятия этого предмета и типа</legend><p>Оставьте всё включённым либо отметьте только заменяемые занятия. Семинары и другие типы сохраняются.</p>${own.map(e=>`<label class="checkbox-label"><input name="hide" type="checkbox" value="${esc(e.id)}" ${old?.hideSeriesIds?.includes(e.id)?'checked':''}>Скрыть: ${days[e.recurrence.weekdays[0]-1]} · ${e.time.startsAt} · ${esc(e.title)}</label>`).join('')||'<p>Совпадающих занятий своей группы нет.</p>'}</fieldset><details><summary>Официальный источник</summary><p>${esc(schedule.importMeta.workbook)} · ${esc(series.source.ranges.join(', '))}</p><blockquote>${esc(series.source.rawText)}</blockquote></details><button class="primary full">${old?'Сохранить выбор':'Добавить выбранную серию'}</button></form>`);
    document.querySelector('#individual-choice').onsubmit=e=>{e.preventDefault();const v=new FormData(e.target);mutate(()=>{const dates=String(v.get('dates')).split(',').map(d=>d.trim()).filter(Boolean),excludeDates=String(v.get('excludeDates')||'').split(',').map(d=>d.trim()).filter(Boolean),from=v.get('from'),to=v.get('to'),weekdays=v.getAll('weekday').map(Number);if(!validDate(from)||!validDate(to)||from>to||[...dates,...excludeDates].some(d=>!validDate(d)||d<from||d>to))throw Error('Проверьте даты выбора.');if(!dates.length&&!weekdays.length)throw Error('Выберите дни или конкретные даты.');const fields={id:old?.id||crypto.randomUUID(),subject:v.get('subject').trim(),from,to,weekdays,dates,excludeDates,hideSeriesIds:v.getAll('hide')};if(old)Object.assign(getState().personalSelections.find(s=>s.id===old.id),fields);else addPersonalSelection(getState(),schedule,series,fields);document.querySelector('#dialog').close();toast('Личный выбор сохранён. Пересечения видны в дне.');});};
  }
  async function search(){
    if(loading)return;loading=true;toast('Загружаем поддерживаемые источники для поиска…');
    try{const catalog=await loadCatalog(base);const results=await Promise.allSettled(catalog.sources.filter(s=>s.status==='ok').map(s=>sourceCandidate(s,base,{overrides:{}})));loaded=results.filter(r=>r.status==='fulfilled').map(r=>r.value);failures=results.filter(r=>r.status==='rejected').map(r=>r.reason.message);}
    catch(e){failures=[e.message];}finally{loading=false;}
    modal('Добавить занятия другой группы',`<form id="individual-search"><label>Предмет<input name="query" placeholder="Например, математический анализ" autofocus></label><label>Тип<select name="kind"><option value="">Все типы</option>${Object.entries(kinds).map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select></label><label>Группа (необязательно)<input name="group" placeholder="Б01-601"></label><button class="primary full">Найти серии</button></form><p class="section-caption">Поиск по ${loaded.length} источникам. ${failures.length?'Не все источники доступны: '+esc(failures.join('; ')):''} Добавляется только выбранная серия, а не весь предмет.</p><div id="individual-results"></div>`);
    document.querySelector('#individual-search').onsubmit=e=>{e.preventDefault();const v=new FormData(e.target),query=subjectKey(v.get('query')),group=subjectKey(v.get('group')),kind=v.get('kind');const matches=loaded.flatMap(schedule=>schedule.series.filter(s=>subjectKey(s.title).includes(query)&&(!kind||s.kind===kind)&&(!group||s.cohorts.some(c=>subjectKey(c.groupId).includes(group)))).map(series=>({schedule,series}))).slice(0,120);
      const result=document.querySelector('#individual-results');result.innerHTML=matches.map(({series:s},i)=>`<button class="catalog-item" data-result="${i}" ${s.blocked?'disabled':''}><strong>${esc(s.title)} · ${esc(kinds[s.kind])}</strong><small>${esc(s.cohorts.map(c=>c.groupId).join(', '))}</small><small>${s.recurrence.weekdays.map(d=>days[d-1]).join(', ')} · ${s.time.startsAt}–${s.time.endsAt} · ${esc(s.instructors?.join(', ')||'')}${s.blocked?' · источник требует уточнения':''}</small></button>`).join('')||'<p>Совпадений нет. Попробуйте часть названия.</p>';result.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{const {schedule,series}=matches[Number(b.dataset.result)];choose(schedule,series);});};
  }
  async function manage(){
    let message='';const state=getState();
    try{const catalog=await loadCatalog(base);for(const [id,source] of Object.entries(state.academicSources||{})){const descriptor=catalog.sources.find(s=>s.id===id);if(!descriptor||descriptor.status!=='ok'){message+='Источник '+source.schedule.importMeta.workbook+' недоступен. ';continue;}if(descriptor.sha256!==source.schedule.importMeta.hash){const candidate=await sourceCandidate(descriptor,base,{schedule:source.schedule,overrides:{}}),diff=importDiff(source.schedule,candidate);updates.set(id,{candidate,diff});}}}catch(e){message='Нет связи с источниками; сохранённые выборы доступны.';}
    modal('Мои выборы и источники',`<button class="primary full" data-individual="search">Добавить занятия</button><p>${esc(message)}</p>${[...updates].map(([id,{diff}])=>`<p class="notice">Новая версия источника · ${diff.filter(d=>d.before&&d.type!=='unchanged').length} изменений выбранных серий <button class="secondary" data-review-source="${esc(id)}">Просмотреть</button></p>`).join('')}${state.personalSelections?.map(s=>`<div class="study-summary"><strong>${esc(s.subject)}</strong><p>${s.from} — ${s.to} · ${s.disabled?'выключено':s.dates?.length?s.dates.join(', '):s.weekdays.map(d=>days[d-1]).join(', ')}${state.academicSources[s.sourceId].missing?.includes(s.seriesId)?' · Серия исчезла из источника: показана последняя сохранённая версия.':''}</p><button class="secondary" data-edit-selection="${esc(s.id)}">Дни / даты / предмет</button><button class="subtle" data-toggle-selection="${esc(s.id)}">${s.disabled?'Вернуть выбор':'Отменить выбор и вернуть свои занятия'}</button></div>`).join('')||'<p>Личных выборов пока нет.</p>'}`);
    document.querySelectorAll('[data-edit-selection]').forEach(b=>b.onclick=()=>{const x=state.personalSelections.find(s=>s.id===b.dataset.editSelection),sc=state.academicSources[x.sourceId].schedule;choose(sc,sc.series.find(s=>s.id===x.seriesId),x);});
    document.querySelectorAll('[data-toggle-selection]').forEach(b=>b.onclick=()=>mutate(()=>{const x=getState().personalSelections.find(s=>s.id===b.dataset.toggleSelection);x.disabled=!x.disabled;document.querySelector('#dialog').close();}));
    document.querySelectorAll('[data-review-source]').forEach(b=>b.onclick=()=>{const id=b.dataset.reviewSource,{candidate,diff}=updates.get(id);modal('Изменения выбранных занятий',`<p>Личные дни, даты, исключения и связанные задачи сохранятся. Исчезнувшие серии останутся с предупреждением.</p>${diff.filter(d=>d.before&&d.type!=='unchanged').map(d=>`<p>${esc(d.before.title)} · ${d.type==='removed'?'исчезло':'изменено'}</p><details><summary>До / после: время, повторение и исходный текст</summary>${reviewSeries(d.before)}${d.after?reviewSeries(d.after):'<p>Серия отсутствует в новой книге.</p>'}</details><p></p>`).join('')||'<p>Выбранные серии не изменились.</p>'}<button class="primary full" id="individual-update-confirm">Применить обновление</button>`);document.querySelector('#individual-update-confirm').onclick=()=>mutate(()=>{updatePersonalSource(getState(),id,candidate,diff);updates.delete(id);document.querySelector('#dialog').close();});});
  }
  function attendance(){const state=getState();modal('Какие занятия вы посетили?',`<form id="attendance-choice"><p>Из-за пересечений нельзя предположить посещение всех занятий. Отметьте посещённые; можно оставить всё пустым.</p>${state.pendingAttendance.map(p=>`<label class="checkbox-label"><input type="checkbox" name="attended" value="${esc(p.event.id)}">${p.event.date} · ${p.event.time.startsAt} · ${esc(p.event.title)}</label>`).join('')}<button class="primary full">Подтвердить и создать задания</button></form>`);document.querySelector('#attendance-choice').onsubmit=e=>{e.preventDefault();const chosen=new Set(new FormData(e.target).getAll('attended'));mutate(()=>{const s=getState();s.attendance??={};for(const p of s.pendingAttendance)s.attendance[p.event.id]=chosen.has(p.event.id);catchUp(s,now());document.querySelector('#dialog').close();});};}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-individual]');if(!b)return;if(b.dataset.individual==='search')search();if(b.dataset.individual==='manage')manage();if(b.dataset.individual==='attendance')attendance();});
}
